# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            BlackDoc
tagline:          BlackDoc
description:      "Used to be a Hacker, more Geeker now."
url:              https://github.com/karloespiritu/blackdoc
baseurl:          /

author:
  name:           'Chansonyan'
  url:            https://twitter.com/karloespiritu

paginate:         35

gems: [jekyll-paginate]

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/chansonyan/BlackDoc
